### ISSUE TITLE
How to validate values?

### ISSUE THREAD

**Issue by micahjon** [jbreckmckye/trkl#5]
Hi, first off, love the conciseness of this library. Nicely done.

Wondering if you have recommendations for how to restrict that valid values for an observable. For instance, let's say I want to restrict an observable to just integers, or to two values, e.g. `light` or `dark` for my theme.

I'm guessing this is a common use case, and just wondered if there was an ergonomic way of doing it once for an observable so invalid values are rejected or at least reported.

Thanks!

**Comment by jbreckmckye** [comment]
The easiest way would be to use TypeScript and enforce this at compile time. You can pass a type to an observable upon initialisation.

This should work:

```typescript
type Theme =
  | 'light'
  | 'dark'

const theme = trkl<Theme>('light');
```

If you wanted to do this at _runtime_, I guess you could have an `input` observable and a `validated` observable, e.g.

```javascript
function filter (observable, fn) {
  return trkl.from(state => {
    observable.subscribe(val => {
      if (fn(val)) state(val);
    }, true);
  })
}

const themeInput = trkl('light');
const theme = filter(themeInput, val =>
  ['light', 'dark'].includes(val)
);
```

**Comment by micahjon** [comment]
Hmm, good call, doing this at compile-time makes sense. Appreciate the code samples.
